### ISSUE TITLE
Command to run the FixMatch

### ISSUE THREAD

**Issue by shreejalt** [YBZh/Bridging_UDA_SSL#1]
Hi, 
Thanks a lot for your work. 

Can you give me the simple command to run the FixMatch on DomainNet/Office dataset without disturl? I have two GPUs

Or If I want to use FixMatch in the original Repo on One GPU, what changes shall I need to do in the original Transfer Learning Library Repo?

**Comment by YBZh** [comment]
Please refer to: https://github.com/YBZh/Bridging_UDA_SSL/blob/main/examples/FixMatch.sh
Note that my original implementation is based on FOUR GPUs,  so maybe you need to modify the --batchsize and --base_lr to adapt to One GPU.
